### ISSUE TITLE
Options shows blank page

### ISSUE THREAD

**Issue by jbolster** [DanAtkinson/Fuskr#14]
I only just noticed this when I was working on Fuskr (had some time, started doing some angular goodness on it). Thought it was my local but a clean install of Fuskr pops it up too.

Does this happen for you too, @DanAtkinson ?

`Uncaught SyntaxError: missing ) after argument list    options.htm:3`

Chrome: Version 49.0.2623.112 m

**Comment by DanAtkinson** [comment]
Resolved by @jbolster so closing.

Thanks!
