### ISSUE TITLE
The bottom info container has disappeared

### ISSUE THREAD

**Issue by DanAtkinson** [DanAtkinson/Fuskr#17]
I'll probably look at it myself, but I'm currently testing the extension and noticed that the bottom info container has disappeared.

@jbolster Is there a reason it's no longer there or was it just removed. I don't mind if it's a deliberate action, but would like to know either way as I can't see any mention of it in the commits.

Thanks, Dan

**Comment by jbolster** [comment]
Whoops. Didn't mean to remove that in that commit.

Well, I was intending to eventually remove it while toying with styling
ideas for the images page (minimal fixed header, etc).

I'll fix that up and add it in :)

**Comment by DanAtkinson** [comment]
I don't mind. If you intended to remove it to reduce screen space, that's okay.

I was also looking to hide the images that haven't loaded yet but that's not for this issue...

**Comment by jbolster** [comment]
Adding it back in for the mean time, at least :)
