### ISSUE TITLE
+/- context menu doesn't appear on image links

### ISSUE THREAD

**Issue by DanAtkinson** [DanAtkinson/Fuskr#18]
**Steps to reproduce:**
1. Go to http://www.evipic.eviland.com/Comments/Images/Romantic/.
2. Right click on one of the image links.

**What I expect to see:**
The '+ / -', '+', and '-' context menu items, along with 'Manual', 'Options' and 'Recent'.

**What I see instead:**
Just the 'Manual', 'Options' and 'Recent' context menu items.

@jbolster Would any of your recent changes have affected this?

**Comment by DanAtkinson** [comment]
@jbolster Ignore that. I've just tested it in 2.7 and it doesn't show the '+ / -' options there either.

How odd!

**Comment by jbolster** [comment]
Shouldn't have. I didn't work on the background javascript

**Comment by DanAtkinson** [comment]
You did (modified routing for history), but the issue appears to be the targetUrlPatterns.

The page in question uses relative urls which causes a problem.

See the targetUrlPattern being generated: `'*://*/*' + i + '*'` 

It expects the protocol and domain in the url string, so the links returned (which is a very common Apache directory listing page) aren't "fuskable". Boo. :(

**Comment by DanAtkinson** [comment]
The problem was the contextType. For whatever reason, Chrome didn't infer that the '.jpg' links on the page were actually links, so I modified the contextType array to be `"image", "video", "audio", "link"`.

This does mean that videos and audio will show as fuskable for now, but I'll get around to implementing that particular feature eventually.

**Comment by jbolster** [comment]
Nice!
