### ISSUE TITLE
Use npm/bower

### ISSUE THREAD

**Issue by DanAtkinson** [DanAtkinson/Fuskr#23]
My personal preference is to use bower but I'm going to need to use grunt so I'll just use npm right now.

I'd also like to make use of grunt to perform a variety of functions:
- Build a single, compressed JS file.
- Build release zip file.
- Perform unit tests.

**Comment by jbolster** [comment]
I'm always in two minds of npm/bower for smaller projects. It always seems to be a bit of a hurdle to development (i.e. the grunt file I have downloads 40MB into node_modules before getting started).

That said, it's becoming more common place and it'd be handy enough for building out the release file, if anything :)

Found this which looks like a decent enough workflow too: http://martijnheesters.nl/grunt-chrome-extension-development/

**Comment by DanAtkinson** [comment]
This is fair. However, the scope of the application has been increasing, and I'm a little concerned that the tests that you spent so much time on aren't being run, and we then potentially run the risk of breaking the extension for others as some of the coming changes can potentially alter the application quite considerably.

I'm looking to compress/minify the JS and also build up the relevant steps to perform a release of the extension as well, but recognise that this step isn't so important.

**Comment by DanAtkinson** [comment]
Implementation of `uglify` is impossible right now because [UglifyJS2](https://github.com/mishoo/UglifyJS2) (upon which [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify) is built) doesn't support ES6/Harmony right now, so nice things like arrow functions (aka lambda `=>`) cause the compiler to fail.

**Comment by jbolster** [comment]
Closing this issue because PR#27 is merged
