### ISSUE TITLE
'This extension may have been corrupted' error when clicking on options

### ISSUE THREAD

**Issue by jbolster** [DanAtkinson/Fuskr#26]
Steps:
1. Install Fuskr from chrome webstore
2. Right click and go to 'Options' on Fuskr (This also applied when going to options through chrome://extensions)

Result: Chrome throws a message of 'This extension may have been corrupted.' beside the extension. Clicking repair re-installs Fuskr and everything is fine.

This only applies when Fuskr is downloaded from the webstore. Loading it unpacked or loading a local packed version doesn't result in the same way. Only the 'Options' page causes this. Actual use of Fuskr doesn't cause the same issue.

**Comment by mskadu** [comment]
and .. tested on "Version 60.0.3112.101 (Official Build) (64-bit)" running in Win10, if it helps.

**Comment by jbolster** [comment]
@DanAtkinson - I think this will have been fixed with all of the option changes (hopefully!) but as it only happens on the downloaded version, I'll leave this issue open until after the next version is released.

**Comment by jbolster** [comment]
I'll close this issue for now - if people are still having issues, then please just comment or reopen.
