### ISSUE TITLE
Task: Fix build to run with linters

### ISSUE THREAD

**Issue by jbolster** [DanAtkinson/Fuskr#28]
Currently `grunt --force` needs to be runin order to pass the linting.

SASS/HTML/JS files all have issues at the moment.

When complete, ensure that travis config isn't running with `--force`

**Comment by DanAtkinson** [comment]
Hi Jonny,

Did you commit the gruntfile? I can't see any commits for it.

Thanks, Dan

**Comment by jbolster** [comment]
It's in this pull-request: https://github.com/DanAtkinson/Fuskr/pull/27/files

**Comment by DanAtkinson** [comment]
Ah, okay. You can accept your own pull requests on this repo. :-)

**Comment by DanAtkinson** [comment]
Hi @jbolster,

I don't know if it helps or not, but I use [Brackets](http://brackets.io/) which includes jslint when editing. Be sure to install an extension like "mitchellsimoens.file-tree-exclude" which will ignore large folders like node_modules and bower_modules.

Thanks, Dan

**Comment by jbolster** [comment]
:) Yeah, I still think it's good for a thumbs up. I'll just merge ALL THE THINGS next time ;)

I use Atom with all the linters and that picks up on the config files that I've checked in (as does the grunt tasks). It also ignores everything that's in the .gitignore file.

Sadly, most of the code here is pre-Atom-usage so needs to be poked in some form or another. Currently refactoring the JS out so that'll fix a lot during that process.
