### ISSUE TITLE
Missing from Chrome Web Store

### ISSUE THREAD

**Issue by AllAstronauts** [DanAtkinson/Fuskr#53]
@DanAtkinson just a ping your way. Not sure when this happened but Fuskr has been nulled from the Chrome Web Store.

**Comment by DanAtkinson** [comment]
Hi there,

That's correct. I removed it from the store and I addressed it here:
https://github.com/DanAtkinson/Fuskr/issues/44#issuecomment-644381586

I will look to update the readme at some point.
